### ISSUE TITLE
show hint that user/token is not set if zeta can't access github

### ISSUE THREAD

**Issue by thinkberg** [moviepilot/zeta#1]
instead of: /Users/leo/.rvm/gems/ruby-2.1.6/gems/zeta-0.2.2/lib/zeta/local_or_remote_file.rb:36:in `http_get': Error 404 (RuntimeError)

**Comment by jayniz** [comment]
The failed url is now printed along with "Error: 404", that should suffice (github for example just returns a 404 and not 401 or such, so we can't differentiate between not found and not authorized).
