### ISSUE TITLE
the local publish/consume.mson can't be copied on check due to missing directory

### ISSUE THREAD

**Issue by thinkberg** [moviepilot/zeta#13]
the "cp" fails, because the directory in .cache for the local project is missing (needs to be created?)

**Comment by jayniz** [comment]
which command did you issue?

**Comment by thinkberg** [comment]
zeta -e development full_check
(first time)

**Comment by jayniz** [comment]
i deleted my contracts `.cache` dir, issued that command, and it worked fine. will hop over to your desk in a minute
