### ISSUE TITLE
Service denomination in publish.mson should either be ignored or displayed as error

### ISSUE THREAD

**Issue by thinkberg** [moviepilot/zeta#2]
This entry in publish.mson

```# Tower:SocialEvent```

results in a consumer not being satisfied.

**Comment by jayniz** [comment]
The publish specification must not contain the service name, so `# Tower:SocialEvent` in `tower`'s `publish.mson` should just read `# SocialEvent`. Perhaps zeta should ignore/strip the service name in publish specifications this or refuse to parse the MSON when one is present.
